DROP TABLE IF EXISTS nobel_win;

CREATE TABLE nobel_win (
    YEAR INT,
    SUBJECT VARCHAR(50),
    WINNER VARCHAR(100),
    COUNTRY VARCHAR(50),
    CATEGORY VARCHAR(50)
);

INSERT INTO nobel_win (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
(1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
(1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
(1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
(1973, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT');

SELECT * FROM nobel_win
WHERE SUBJECT NOT LIKE 'P%';